#!/bin/bash

if [ -z "$1" ]
then
    echo "Please specify security group id";
    exit;
else
    SG=$1
fi

aws ec2 describe-security-groups --group-ids $SG | jq '.SecurityGroups[].IpPermissions[] | {port: .FromPort, ip: .IpRanges}'