#!/bin/bash

DOTFILE_PATH=`pwd`"/dotfiles/"
DOTFILES=`ls -A $DOTFILE_PATH`

for item in $DOTFILES
do
    if [ -d "$DOTFILE_PATH$item" ]
    then
        echo cp -r $DOTFILE_PATH$item $HOME
    else
        echo ln -sf $DOTFILE_PATH$item $HOME
    fi
done
exit;

sudo apt update
sudo apt install hub jq wget tmux vim

wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -O $HOME/.git-completion.bash
wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -O $HOME/.git-prompt.sh


