#!/bin/bash

DOTFILE_PATH=`pwd`"/dotfiles/"
DOTFILES=`ls -A $DOTFILE_PATH`

for item in $DOTFILES
do
    if [ -d "$DOTFILE_PATH$item" ]
    then
        cp -r $DOTFILE_PATH$item $HOME
    else
        ln -sf $DOTFILE_PATH$item $HOME
    fi
done

sudo apt update
sudo apt install -y hub jq wget tmux vim
sudo snap install hub --classic

wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -O $HOME/.git-completion.bash
wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -O $HOME/.git-prompt.sh

sudo apt install -y fonts-roboto fonts-noto fonts-ricty-diminished
