#!/bin/bash

DOTFILE_PATH=`pwd`"/dotfiles/"
DOTFILES=`ls -A $DOTFILE_PATH`

for item in $DOTFILES
do
    if [ -d "$DOTFILE_PATH$item" ]
    then
        cp -r $DOTFILE_PATH$item $HOME
    else
        ln -sf $DOTFILE_PATH$item $HOME
    fi
done

sudo apt update
sudo apt install -y hub jq wget tmux vim xclip
sudo snap install hub --classic

wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -O $HOME/.git-completion.bash
wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -O $HOME/.git-prompt.sh

sudo apt install -y fonts-roboto fonts-noto fonts-ricty-diminished

#php compilation
sudo apt install -y libssl-dev pkg-config libxml2-dev libkrb5-dev libsqlite3-dev libbz2-dev libcurl4-nss-dev
sudo apt install -y libpng-dev libjpeg-dev libonig-dev libreadline-dev libtidy-dev libxslt1-dev libzip-dev libffi-dev

#xdebug compilation
sudo apt install -y autoconf automake

#hstr installation
sudo add-apt-repository ppa:ultradvorka/ppa && sudo apt update && sudo apt install -y hstr
